### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by jingliancui** [sunnamed434/BitMono#156]
Version：
BitMono-v0.20.0-alpha.35-CLI-net6.0

DLLs (this is the dll from .net8 console app):
[workspace.zip](https://github.com/sunnamed434/BitMono/files/13427151/workspace.zip)

OS:
Win 11

```
[2023-11-21 22:05:48 INF][BitMono.CLI.Modules.CLIObfuscationNeedsFactory] Please, specify file or drag-and-drop in BitMono CLI
D:\workspace\ConsoleSampleApp.dll
[2023-11-21 22:06:21 INF][BitMono.CLI.Modules.CLIObfuscationNeedsFactory] File successfully specified: D:\workspace\ConsoleSampleApp.dll
[2023-11-21 22:06:21 INF][BitMono.CLI.Modules.CLIObfuscationNeedsFactory] Dependencies (libs) directory was automatically found in: D:\workspace\libs!
[2023-11-21 22:06:21 INF][BitMono.CLI.Program] File: D:\workspace\ConsoleSampleApp.dll
[2023-11-21 22:06:21 INF][BitMono.CLI.Program] Dependencies (libs): D:\workspace\libs
[2023-11-21 22:06:21 INF][BitMono.CLI.Program] Everything is seems to be ok, starting obfuscation..
[2023-11-21 22:06:21 INF][BitMono.CLI.Program]
       ___  _ __  __  ___
      / _ )(_) /_/  |/  /__  ___  ___
     / _  / / __/ /|_/ / _ \/ _ \/ _ \
    /____/_/\__/_/  /_/\___/_//_/\___/
    https://github.com/sunnamed434/BitMono
    BitMono v0.20.0.0
[2023-11-21 22:06:22 INF][BitMono.Obfuscation.BitMonoObfuscator] Module ConsoleSampleApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[2023-11-21 22:06:22 INF][BitMono.Obfuscation.BitMonoObfuscator] Module Target Framework: .NETCoreApp
[2023-11-21 22:06:22 INF][BitMono.Obfuscation.BitMonoObfuscator] PE TimeDateStamp: 11/22/2067 02:05:03
[2023-11-21 22:06:22 INF][BitMono.Obfuscation.BitMonoObfuscator] Module culture: ["u", "n", "k", "n", "o", "w", "n"]
[2023-11-21 22:06:22 FTL][BitMono.Obfuscation.BitMonoObfuscator] No one protection were detected, please specify or enable them in protections.json!
[2023-11-21 22:06:22 FTL][BitMono.Obfuscation.BitMonoObfuscator] Obfuscation stopped! Something went wrong!
Something went wrong! System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'D:\workspace\output' with working directory 'D:\BitMono-v0.20.0-alpha.35-CLI-net6.0'. 拒绝访问。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at BitMono.CLI.Program.Main(String[] args) in D:\a\BitMono\BitMono\src\BitMono.CLI\Program.cs:line 65
   at BitMono.CLI.Program.Main(String[] args) in D:\a\BitMono\BitMono\src\BitMono.CLI\Program.cs:line 65
Enter anything to exit!
```

**Comment by jingliancui** [comment]
I can see BitMono will create the output blank folder.

**Comment by sunnamed434** [comment]
Try to set `OpenFileDestinationInFileExplorer` to `false` in `obfuscation.json`, try to reproduce the same BitMono usage as you did before, and let me know the results

**Comment by jingliancui** [comment]
Hi @sunnamed434 , sorry it doesn't work, plus there is no more detail logs:

```
[2023-11-22 19:09:34 INF][BitMono.CLI.Program] File: D:\workspace\ConsoleSampleApp.dll
[2023-11-22 19:09:34 INF][BitMono.CLI.Program] Dependencies (libs): D:\workspace\libs
[2023-11-22 19:09:34 INF][BitMono.CLI.Program] Everything is seems to be ok, starting obfuscation..
[2023-11-22 19:09:34 INF][BitMono.CLI.Program]
       ___  _ __  __  ___
      / _ )(_) /_/  |/  /__  ___  ___
     / _  / / __/ /|_/ / _ \/ _ \/ _ \
    /____/_/\__/_/  /_/\___/_//_/\___/
    https://github.com/sunnamed434/BitMono
    BitMono v0.20.0.0
[2023-11-22 19:09:34 INF][BitMono.Obfuscation.BitMonoObfuscator] Module ConsoleSampleApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[2023-11-22 19:09:34 INF][BitMono.Obfuscation.BitMonoObfuscator] Module Target Framework: .NETCoreApp
[2023-11-22 19:09:34 INF][BitMono.Obfuscation.BitMonoObfuscator] PE TimeDateStamp: 11/22/2067 02:05:03
[2023-11-22 19:09:34 INF][BitMono.Obfuscation.BitMonoObfuscator] Module culture: ["u", "n", "k", "n", "o", "w", "n"]
[2023-11-22 19:09:35 FTL][BitMono.Obfuscation.BitMonoObfuscator] No one protection were detected, please specify or enable them in protections.json!
[2023-11-22 19:09:35 FTL][BitMono.Obfuscation.BitMonoObfuscator] Obfuscation stopped! Something went wrong!
Enter anything to exit!
```

**Comment by sunnamed434** [comment]
It works but not as you think, you need to enable at least 1 protection in `protections.json`

**Comment by jingliancui** [comment]
awesome! you are right, how about let me supplement those info in readme?

**Comment by sunnamed434** [comment]
Sure, why not

**Comment by jingliancui** [comment]
https://github.com/sunnamed434/BitMono/pull/157
Create one PR to deal with the access denied.
Will create the 2nd PR for protection stuff

**Comment by jingliancui** [comment]
dev branch PR: https://github.com/sunnamed434/BitMono/pull/158
Create one PR to deal with the access denied.
Will create the 2nd PR for protection stuff

**Comment by jingliancui** [comment]
https://github.com/sunnamed434/BitMono/pull/159
the second pr for protection stuff.

**Comment by jingliancui** [comment]
feel free to close this issue, thanks.
