### ISSUE TITLE
Failed to resolve dependency: System.Runtime & An error occured while opening the destination file in explorer!

### ISSUE THREAD

**Issue by sefinek24** [sunnamed434/BitMono#200]
I really don't know why this isn't working. The DLL file is being generated, but it doesn't work after being replaced. Running `BitMono.CLI.exe` with administrator privileges doesn't help either. Even with the correct permissions, errors still appear saying that permissions are missing.

Thanks for help

```
[2024-09-01 22:02:26 INF][BitMono.CLI.Modules.ReadlineObfuscationNeedsFactory] Please, specify file or drag-and-drop in BitMono CLI
"C:\Users\Sefinek\Desktop\net8.0-windows\XXXX.dll"
[2024-09-01 22:02:31 INF][BitMono.CLI.Modules.ReadlineObfuscationNeedsFactory] File successfully specified: C:\Users\Sefinek\Desktop\net8.0-windows\XXXX.dll
[2024-09-01 22:02:31 INF][BitMono.CLI.Modules.ReadlineObfuscationNeedsFactory] Please, specify dependencies (libs) path:
C:\Users\Sefinek\Desktop\net8.0-windows
[2024-09-01 22:02:34 INF][BitMono.CLI.Modules.ReadlineObfuscationNeedsFactory] Dependencies (libs) successfully specified: C:\Users\Sefinek\Desktop\net8.0-windows!
[2024-09-01 22:02:34 INF][BitMono.CLI.Program] File: C:\Users\Sefinek\Desktop\net8.0-windows\XXXX.dll
[2024-09-01 22:02:34 INF][BitMono.CLI.Program] Dependencies (libs): C:\Users\Sefinek\Desktop\net8.0-windows
[2024-09-01 22:02:34 INF][BitMono.CLI.Program] Everything is seems to be ok, starting obfuscation..
[2024-09-01 22:02:34 INF][BitMono.CLI.Program]
       ___  _ __  __  ___
      / _ )(_) /_/  |/  /__  ___  ___
     / _  / / __/ /|_/ / _ \/ _ \/ _ \
    /____/_/\__/_/  /_/\___/_//_/\___/
    https://github.com/sunnamed434/BitMono
    BitMono v0.26.0.0
[2024-09-01 22:02:35 INF][BitMono.Obfuscation.BitMonoObfuscator] Module XXXX, Version=8.1.7.0, Culture=neutral, PublicKeyToken=null
[2024-09-01 22:02:35 INF][BitMono.Obfuscation.BitMonoObfuscator] Module Target Framework: .NETCoreApp 8.0
[2024-09-01 22:02:35 INF][BitMono.Obfuscation.BitMonoObfuscator] Module PE TimeDateStamp: 10/16/2050 03:08:27
[2024-09-01 22:02:35 INF][BitMono.Obfuscation.BitMonoObfuscator] Module culture: unknown
[2024-09-01 22:02:35 INF][BitMono.Obfuscation.BitMonoObfuscator] BitMono running on: OS: Microsoft Windows NT 10.0.19045.0, .NET 8.0.8 v8.0, x64 bits
[2024-09-01 22:02:36 INF][BitMono.Obfuscation.Notifiers.ProtectionsNotifier] (8) Enabled protection(s): AntiILdasm, AntiDe4dot, ObjectReturnType, NoNamespaces, FullRenamer, AntiDebugBreakpoints, BillionNops, StringsEncryption
[2024-09-01 22:02:36 INF][BitMono.Obfuscation.Notifiers.ProtectionsNotifier] (9) Disabled protection(s): AntiDecompiler, BitDecompiler, BitDotNet, BitMethodDotnet, BitMono, BitTimeDateStamp, CallToCalli, DotNetHook, UnmanagedString
[2024-09-01 22:02:36 INF][BitMono.Obfuscation.BitMonoObfuscator] Starting resolving dependencies...
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: Stella.Utils, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: CliWrap, Version=3.6.6.0, Culture=neutral, PublicKeyToken=1c4a4fc2d6886e5a
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: DiscordRPC, Version=1.2.1.24, Culture=neutral, PublicKeyToken=null
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: ByteSize, Version=2.1.2.0, Culture=neutral, PublicKeyToken=036f71e5fc483cd1
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: NAudio.WinMM, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: NAudio, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: NAudio.Core, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: Microsoft.Web.WebView2.WinForms, Version=1.0.2739.15, Culture=neutral, PublicKeyToken=2a8ab48044d2601e
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: Microsoft.Web.WebView2.Core, Version=1.0.2739.15, Culture=neutral, PublicKeyToken=2a8ab48044d2601e
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: System.Runtime.Caching, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: Stella.Telemetry, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: Hardware.Info, Version=100.1.1.0, Culture=neutral, PublicKeyToken=3130d442e696f124
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: LibVLCSharp, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: LibVLCSharp.WinForms, Version=3.9.0.0, Culture=neutral, PublicKeyToken=null
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Successfully resolved dependency: ICSharpCode.SharpZipLib, Version=1.4.2.13, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Text.RegularExpressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Drawing.Common, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Threading, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: Microsoft.Win32.Registry, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Collections, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Windows.Forms, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Security.Cryptography, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Diagnostics.Process, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Net.Requests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Net.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.ComponentModel.TypeConverter, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.IO.Compression, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Drawing.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.IO.Pipes, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Net.WebSockets.Client, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.ComponentModel.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Net.WebSockets, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Windows.Extensions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Runtime.InteropServices, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Windows.Forms.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Linq, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Threading.Thread, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Diagnostics.FileVersionInfo, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: Microsoft.CSharp, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Security.Principal.Windows, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Collections.NonGeneric, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Net.NetworkInformation, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Net.ServicePoint, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Memory, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.IO.Compression.ZipFile, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[2024-09-01 22:02:37 WRN][BitMono.Obfuscation.BitMonoObfuscator] Failed to resolve dependency: System.Security.Cryptography.ProtectedData, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] References resolve have been completed!
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] Executing Protections... this could take for a while...
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] AntiILdasm -> OK
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] AntiDe4dot -> OK
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] ObjectReturnType -> OK
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] NoNamespaces -> OK
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] FullRenamer -> OK
[2024-09-01 22:02:37 INF][BitMono.Obfuscation.BitMonoObfuscator] AntiDebugBreakpoints -> OK
[2024-09-01 22:02:38 INF][BitMono.Obfuscation.BitMonoObfuscator] BillionNops -> OK
[2024-09-01 22:02:40 INF][BitMono.Obfuscation.BitMonoObfuscator] StringsEncryption -> OK
[2024-09-01 22:02:40 INF][BitMono.Obfuscation.BitMonoObfuscator] The protected module was saved in C:\Users\Sefinek\Desktop\net8.0-windows\output
[2024-09-01 22:02:40 INF][BitMono.Obfuscation.BitMonoObfuscator] Protections have been executed!
[2024-09-01 22:02:40 INF][BitMono.Obfuscation.BitMonoObfuscator] Since obfuscation elapsed: 00:00:04.1420316
[2024-09-01 22:02:40 ERR][BitMono.CLI.Program] An error occured while opening the destination file in explorer!
System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'C:\Users\Sefinek\Desktop\net8.0-windows\output' with working directory 'C:\Users\Sefinek\Desktop\bitmono'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at BitMono.CLI.Program.Main(String[] args) in /home/runner/work/BitMono/BitMono/src/BitMono.CLI/Program.cs:line 71
Enter anything to exit!
```

**Comment by sunnamed434** [comment]
Hi, you can ignore that some dependencies are not resolved, not that important, but if you can provide to bitmono most of your dependencies then obfuscation can be more deeper for your file.

You can also ignore the case about it can't open destination folder, I had same problem with .net 6 and higher specifically, I'll try to figure something out about that.

As I understand after obfuscation your file not working anymore? If it is, try keep only AntiIldasm to ensure it work, if it worked then it means the problem is in one of the features, and try to disable features one by one to find the problem,however I think the problem is in FullRenamer or AntiDebugBreakpoints

**Comment by sefinek24** [comment]
Thanks for the response.

> As I understand after obfuscation your file not working anymore?

yes

How can I add more files for obfuscation in one "cycle"?
![](https://screenshots.sefinek.net/12.09.2024/explorer_I6xTGoAE04bX.png)

**Comment by sunnamed434** [comment]
Hi,

There's currently no way to protect many files at once, if these files "static", same name location etc, you can make a script for example in csproj or Powershell or even in c# to run bitmono process and pass all the stuff into it.

**Comment by sefinek24** [comment]
It's too buggy. I'll stick with my other solution
