### ISSUE TITLE
Cannnot Obfuscate

### ISSUE THREAD

**Issue by 90th** [sunnamed434/BitMono#95]
### BitMono Version

0.10

### .NET Version

.NET 4.7.2

### Description

Fails to obfuscate simple Console application

### Reproduction steps

```bash
1. Run BitMono CLI 
2. Specifed file and libs
3. Get the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
[2023-02-14 08:33:22 INF][BitMono.Obfuscation.BitMonoEngine] Loaded Module Notes.exe
[2023-02-14 08:33:22 INF][BitMono.Obfuscation.ProtectionsNotifier] Enabled protections: FullRenamer, BitDotNet, BitMono
[2023-02-14 08:33:22 WRN][BitMono.Obfuscation.ProtectionsRuntimeMonikerNotifier] [!!!] BitDotNet - Intended for Mono runtime
[2023-02-14 08:33:22 WRN][BitMono.Obfuscation.ProtectionsRuntimeMonikerNotifier] [!!!] BitMono - Intended for Mono runtime
[2023-02-14 08:33:22 WRN][BitMono.Obfuscation.ProtectionsNotifier] Disabled protections: AntiDe4dot, AntiDebugBreakpoints, AntiDecompiler, AntiILdasm, BitMethodDotnet, BitTimeDateStamp, CallToCalli, DotNetHook, NoNamespaces, ObjectReturnType, StringsEncryption
[2023-02-14 08:33:22 INF][BitMono.Obfuscation.BitMonoObfuscator] Running on Microsoft Windows NT 6.2.9200.0, .NETFramework v4.0.30319.42000, x64 bits



File: C:\Users\Owner\Desktop\Folders\Programming\Projects\Notes\bin\Debug\Notes.exe
Dependencies (libs): lib
Everything is seems to be ok, starting obfuscation..
[2023-02-14 08:33:22 INF][BitMono.Obfuscation.BitMonoEngine] Loaded Module Notes.exe
[2023-02-14 08:33:22 INF][BitMono.Obfuscation.ProtectionsNotifier] Enabled protections: FullRenamer, BitDotNet, BitMono
[2023-02-14 08:33:22 WRN][BitMono.Obfuscation.ProtectionsRuntimeMonikerNotifier] [!!!] BitDotNet - Intended for Mono runtime
[2023-02-14 08:33:22 WRN][BitMono.Obfuscation.ProtectionsRuntimeMonikerNotifier] [!!!] BitMono - Intended for Mono runtime
[2023-02-14 08:33:22 WRN][BitMono.Obfuscation.ProtectionsNotifier] Disabled protections: AntiDe4dot, AntiDebugBreakpoints, AntiDecompiler, AntiILdasm, BitMethodDotnet, BitTimeDateStamp, CallToCalli, DotNetHook, NoNamespaces, ObjectReturnType, StringsEncryption
[2023-02-14 08:33:22 INF][BitMono.Obfuscation.BitMonoObfuscator] Running on Microsoft Windows NT 6.2.9200.0, .NETFramework v4.0.30319.42000, x64 bits
Something went wrong! System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at AsmResolver.PE.File.Headers.DosHeader.FromReader(BinaryStreamReader& reader)
   at AsmResolver.PE.File.SerializedPEFile..ctor(BinaryStreamReader& reader, PEMappingMode mode)
   at BitMono.Core.Protecting.Resolvers.AssemblyResolver.Resolve(IEnumerable`1 dependenciesData, ProtectionContext context)
   at BitMono.Obfuscation.BitMonoObfuscator.ResolveDependenciesAsync(ProtectionContext context)
   at BitMono.Core.Protecting.Pipeline.InvokablePipeline.<InvokeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitMono.Obfuscation.BitMonoObfuscator.<ProtectAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitMono.Obfuscation.BitMonoEngine.<StartAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitMono.Obfuscation.BitMonoEngine.<StartAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitMono.Obfuscation.BitMonoEngine.<StartAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitMono.CLI.Program.<Main>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BitMono.CLI.Program.<Main>d__0.MoveNext()
Press any key to exit!
```

### Applications

CLI

### OS

Windows

**Comment by 90th** [comment]
Ohh i see now, thank you very much! 

i was attempting to use the libs from bitmono 🤦🏻

**Comment by sunnamed434** [comment]
> Ohh i see now, thank you very much! 
> 
> i was attempting to use the libs from bitmono 🤦🏻

Very weird that BitMono libs causes such problem
